version: 2

models:

  - name: stg_addresses
    description: Contains address information of a user
    columns:
      - name: address_id
        description: address_id is the primary key for the adresses table
        tests:
          - unique
          - not_null
      - name: zipcode
        description: The zipcode of the address
        tests:
          - field_length:
              length_of_field: 5

  - name: stg_events
    description: Captures each sessions event of a user's activity on the site i.e. add to cart, checkout, navigation between pages
    columns:
      - name: event_id
        description: event_id is the primary key for the event table
        tests:
          - unique
          - not_null
      - name: session_id
        description: session_id unique identifier for each browsing session on the greenery site
        tests:
          - not_null
      - name: user_id
        description: user_id of the user that this event is associated with
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id

  - name: stg_order_items
    description:  Contains information of an order i.e. which product is bought and it's price and qauntity 
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
    columns:
      - name: order_id
        description: order_id and product_id make up the composite primary key for the order_items table
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: order_id and product_id make up the composite primary key for the  order_items table
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        tests:
          - positive_values

  - name: stg_orders
    description:  Contains order details such as order id, shipping & tracking details and estimated delivery
    columns:
      - name: order_id
        description: order_id primary key for the orders table
        tests:
          - unique
          - not_null
      - name: order_cost
        tests:
          - positive_values
      - name: shipping_cost
        tests:
          - positive_values
      - name: order_status
        tests:
          - accepted_values:
              values: ['shipped', 'preparing', 'delivered']
      - name: promo_id
        description: Promo_id of promotion code that is used for an order
        tests:
          - relationships:
              to: ref('stg_promos')
              field: promo_id
      - name: order_total
        description: Total cost of the order including shipping
        tests:
          - positive_values

  - name: stg_product
    description: Contains products we sell and inventory information
    columns:
      - name: product_id
        description: product_id is the primary key for the prodct table
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - positive_values
      - name: inventory
        tests:
          - positive_values

  - name: stg_promos
    description: Captures sales promotion information company is offering on it's products
    columns:
      - name: promo_id
        description: promo_id is the primary key for the promos table
        tests:
          - unique
          - not_null
      - name: discount
        tests:
          - positive_values
      - name: promo_status
        tests:
          - accepted_values:
              values: ['active', 'inactive']

  - name: stg_users
    description: Contains user details; user id and user contact information
    columns:
      - name: user_id
        description: user_id is the primary key for the users table
        tests:
          - unique
          - not_null
      - name: first_name
        description: first name of the user
        tests:
          - not_null
      - name: last_name
        description: last name of the user
        tests:
          - not_null
      - name: address_id
        description: default delivery address for the user
        tests:
          - relationships:
              to: ref('stg_addresses')
              field: address_id
