version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values

  - name: stg_addresses
    description: Contains address information of a user
    columns:
      - name: address_id
        description: "The primary key for adresses table"
        tests:
          - unique
          - not_null

  - name: stg_events
    description: Captures each sessions event aout user activity on the site
    columns:
      - name: event_id
        description: "The primary key for event table"
        tests:
          - unique
          - not_null

  - name: stg_order_items
    description: Contains order information of an order 
    columns:
      - name: order_id
        description: "The primary key for order_items table"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "The primary key for order_items table"
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Contains order details such as order id, shipping & tracking details and estimated delivery
    columns:
      - name: order_id
        description: "The primary key for orders table"
        tests:
          - unique
          - not_null

  - name: stg_product
    description: Contains products we sell and inventory information
    columns:
      - name: product_id
        description: "The primary key for prodct table"
        tests:
          - unique
          - not_null

  - name: stg_promos
    description: Captures sales promotion information company is offering on it's products
    columns:
      - name: promo_id
        description: "The primary key for promos table"
        tests:
          - unique
          - not_null

  - name: stg_users
    description: Contains user details; user id and user contact information
    columns:
      - name: user_id
        description: "The primary key for users table"
        tests:
          - unique
          - not_null